CREATE SEQUENCE OrganizationSequence START 1;
CREATE SEQUENCE UserSequence START 1;
CREATE SEQUENCE CountrySequence START 1;
CREATE SEQUENCE StateSequence START 1;
CREATE SEQUENCE CitySequence START 1;
CREATE SEQUENCE AddressSequence START 1;
CREATE SEQUENCE ContactSequence START 1;