CREATE SEQUENCE AddressSequence START 1;
CREATE SEQUENCE AgencySequence START 1;
CREATE SEQUENCE CitySequence START 1;
CREATE SEQUENCE CountrySequence START 1;
CREATE SEQUENCE StateSequence START 1;
CREATE SEQUENCE SubjectSequence START 1;
CREATE SEQUENCE ModifiedAddressSequence START 1;
