/*PRIMARY KEYS*/
ALTER TABLE "Level" ADD CONSTRAINT "LevelPK" PRIMARY KEY("identifier");

ALTER TABLE "Country" ADD CONSTRAINT "CountryPK" PRIMARY KEY("identifier");

ALTER TABLE "State" ADD CONSTRAINT "StatePK" PRIMARY KEY("identifier");

ALTER TABLE "City" ADD CONSTRAINT "CityPK" PRIMARY KEY("identifier");

ALTER TABLE "Address" ADD CONSTRAINT "AddressPK" PRIMARY KEY("identifier");

ALTER TABLE "Contact" ADD CONSTRAINT "ContactPK" PRIMARY KEY("identifier");

ALTER TABLE "Organization" ADD CONSTRAINT "OrganizationPK" PRIMARY KEY("identifier");

ALTER TABLE "User" ADD CONSTRAINT "UserPK" PRIMARY KEY("identifier");

ALTER TABLE "Token" ADD CONSTRAINT "TokenPK" PRIMARY KEY("identifier");

ALTER TABLE "Ticket" ADD CONSTRAINT "TicketPK" PRIMARY KEY("identifier");

/*FOREIGN KEYS*/

ALTER TABLE "State" ADD CONSTRAINT "StateCountryFK" FOREIGN KEY("country") REFERENCES "Country"("identifier") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "City" ADD CONSTRAINT "CityStateFK" FOREIGN KEY("state") REFERENCES "State"("identifier") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Address" ADD CONSTRAINT "AddressCityFK" FOREIGN KEY("city") REFERENCES "City"("identifier") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Organization" ADD CONSTRAINT "OrganizationAddressFK" FOREIGN KEY("address") REFERENCES "Address"("identifier") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Organization" ADD CONSTRAINT "OrganizationContactFK" FOREIGN KEY("contact") REFERENCES "Contact"("identifier") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "User" ADD CONSTRAINT "UserAddressFK" FOREIGN KEY("address") REFERENCES "Address"("identifier") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "UserContactFK" FOREIGN KEY("contact") REFERENCES "Contact"("identifier") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "UserOrganizationFK" FOREIGN KEY("organization") REFERENCES "Organization"("identifier") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "User" ADD CONSTRAINT "UserLevelFK" FOREIGN KEY("level") REFERENCES "Level"("identifier") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "Token" ADD CONSTRAINT "TokenUserFK" FOREIGN KEY("user") REFERENCES "User"("identifier") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE "Ticket" ADD CONSTRAINT "TicketUserFK" FOREIGN KEY("user") REFERENCES "User"("identifier") ON DELETE CASCADE ON UPDATE CASCADE;


