DROP SEQUENCE IF EXISTS AddressSequence CASCADE;
DROP SEQUENCE IF EXISTS AgencySequence CASCADE;
DROP SEQUENCE IF EXISTS CitySequence CASCADE;
DROP SEQUENCE IF EXISTS CountrySequence CASCADE;
DROP SEQUENCE IF EXISTS StateSequence CASCADE;
DROP SEQUENCE IF EXISTS SubjectSequence CASCADE;
