/*FOREIGN KEYS*/
ALTER TABLE IF EXISTS "State" DROP CONSTRAINT IF EXISTS "StateCountryFK" CASCADE;

ALTER TABLE IF EXISTS "City" DROP CONSTRAINT IF EXISTS "CityStateFK" CASCADE;

ALTER TABLE IF EXISTS "Address" DROP CONSTRAINT IF EXISTS "AddressCityFK" CASCADE;

ALTER TABLE IF EXISTS "Organization" DROP CONSTRAINT IF EXISTS "OrganizationAddressFK" CASCADE;
ALTER TABLE IF EXISTS "Organization" DROP CONSTRAINT IF EXISTS "OrganizationContactFK" CASCADE;

ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserAddressFK" CASCADE;
ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserContactFK" CASCADE;
ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserOrganizationFK" CASCADE;
ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserLevelFK" CASCADE;

ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenUserFK" CASCADE;

ALTER TABLE IF EXISTS "Ticket" DROP CONSTRAINT IF EXISTS "TicketUserFK" CASCADE;

/*PRIMARY KEYS*/
ALTER TABLE IF EXISTS "Level" DROP CONSTRAINT IF EXISTS "LevelPK" CASCADE;

ALTER TABLE IF EXISTS "Country" DROP CONSTRAINT IF EXISTS "CountryPK" CASCADE;

ALTER TABLE IF EXISTS "State" DROP CONSTRAINT IF EXISTS "StatePK" CASCADE;

ALTER TABLE IF EXISTS "City" DROP CONSTRAINT IF EXISTS "CityPK" CASCADE;

ALTER TABLE IF EXISTS "Address" DROP CONSTRAINT IF EXISTS "AddressPK" CASCADE;

ALTER TABLE IF EXISTS "Contact" DROP CONSTRAINT IF EXISTS "ContactPK" CASCADE;

ALTER TABLE IF EXISTS "Organization" DROP CONSTRAINT IF EXISTS "OrganizationPK" CASCADE;

ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserPK" CASCADE;

ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenPK" CASCADE;

ALTER TABLE IF EXISTS "Ticket" DROP CONSTRAINT IF EXISTS "TicketPK" CASCADE;