DROP SEQUENCE IF EXISTS OrganizationSequence CASCADE;
DROP SEQUENCE IF EXISTS UserSequence CASCADE;
DROP SEQUENCE IF EXISTS CountrySequence CASCADE;
DROP SEQUENCE IF EXISTS StateSequence CASCADE;
DROP SEQUENCE IF EXISTS CitySequence CASCADE;
DROP SEQUENCE IF EXISTS AddressSequence CASCADE;
DROP SEQUENCE IF EXISTS ContactSequence CASCADE;