/*FOREIGN KEYS*/
ALTER TABLE IF EXISTS "Address" DROP CONSTRAINT IF EXISTS "AddressCityFK" CASCADE;

ALTER TABLE IF EXISTS "AddressEdification" DROP CONSTRAINT IF EXISTS "AddressEdificationAddressFK" CASCADE;
ALTER TABLE IF EXISTS "AddressEdification" DROP CONSTRAINT IF EXISTS "AddressEdificationTypeFK" CASCADE;

ALTER TABLE IF EXISTS "AddressEdificationDweller" DROP CONSTRAINT IF EXISTS "AddressEdificationDwellerAddressEdificationFK" CASCADE;
ALTER TABLE IF EXISTS "AddressEdificationDweller" DROP CONSTRAINT IF EXISTS "AddressEdificationDwellerSubjectFK" CASCADE;
ALTER TABLE IF EXISTS "AddressEdificationDweller" DROP CONSTRAINT IF EXISTS "AddressEdificationDwellerVerifiedByFK" CASCADE;

ALTER TABLE IF EXISTS "City" DROP CONSTRAINT IF EXISTS "CityStateFK" CASCADE;

ALTER TABLE IF EXISTS "Government" DROP CONSTRAINT IF EXISTS "GovernmentOrganizationFK" CASCADE;

ALTER TABLE IF EXISTS "GovernmentCity" DROP CONSTRAINT IF EXISTS "GovernmentCityGovernmentFK" CASCADE;
ALTER TABLE IF EXISTS "GovernmentCity" DROP CONSTRAINT IF EXISTS "GovernmentCityCityFK" CASCADE;

ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualSubjectFK" CASCADE;
ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualRgAgencyFK" CASCADE;
ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualRgStateFK" CASCADE;
ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualBirthPlaceFK" CASCADE;

ALTER TABLE IF EXISTS "Organization" DROP CONSTRAINT IF EXISTS "OrganizationSubjectFK" CASCADE;

ALTER TABLE IF EXISTS "State" DROP CONSTRAINT IF EXISTS "StateCountryFK" CASCADE;

ALTER TABLE IF EXISTS "SubjectSubject" DROP CONSTRAINT IF EXISTS "SubjectSubjectParentFK" CASCADE;
ALTER TABLE IF EXISTS "SubjectSubject" DROP CONSTRAINT IF EXISTS "SubjectSubjectChildFK" CASCADE;

ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenGovernmentFK" CASCADE;
ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenUserFK" CASCADE;
ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenSubjectSubjectFK" CASCADE;

ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserIndividualFK" CASCADE;
ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserLastLoggedInFK" CASCADE;

/*PRIMARY KEYS*/
ALTER TABLE IF EXISTS "Type" DROP CONSTRAINT IF EXISTS "TypePK" CASCADE;

ALTER TABLE IF EXISTS "Address" DROP CONSTRAINT IF EXISTS "AddressPK" CASCADE;

ALTER TABLE IF EXISTS "AddressEdification" DROP CONSTRAINT IF EXISTS "AddressEdificationPK" CASCADE;

ALTER TABLE IF EXISTS "AddressEdificationDweller" DROP CONSTRAINT IF EXISTS "AddressEdificationDwellerPK" CASCADE;

ALTER TABLE IF EXISTS "Agency" DROP CONSTRAINT IF EXISTS "AgencyPK" CASCADE;

ALTER TABLE IF EXISTS "City" DROP CONSTRAINT IF EXISTS "CityPK" CASCADE;

ALTER TABLE IF EXISTS "Country" DROP CONSTRAINT IF EXISTS "CountryPK" CASCADE;

ALTER TABLE IF EXISTS "Government" DROP CONSTRAINT IF EXISTS "GovernmentPK" CASCADE;

ALTER TABLE IF EXISTS "GovernmentCity" DROP CONSTRAINT IF EXISTS "GovernmentCityPK" CASCADE;

ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualPK" CASCADE;

ALTER TABLE IF EXISTS "Organization" DROP CONSTRAINT IF EXISTS "OrganizationPK" CASCADE;

ALTER TABLE IF EXISTS "State" DROP CONSTRAINT IF EXISTS "StatePK" CASCADE;

ALTER TABLE IF EXISTS "Subject" DROP CONSTRAINT IF EXISTS "SubjectPK" CASCADE;

ALTER TABLE IF EXISTS "SubjectSubject" DROP CONSTRAINT IF EXISTS "SubjectSubjectPK" CASCADE;

ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenPK" CASCADE;

ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserPK" CASCADE;