/*FOREIGN KEYS*/
ALTER TABLE IF EXISTS "Address" DROP CONSTRAINT IF EXISTS "AddressCityFK" CASCADE;

ALTER TABLE IF EXISTS "AddressEdification" DROP CONSTRAINT IF EXISTS "AddressEdificationAddressFK" CASCADE;
ALTER TABLE IF EXISTS "AddressEdification" DROP CONSTRAINT IF EXISTS "AddressEdificationTypeFK" CASCADE;

ALTER TABLE IF EXISTS "AddressEdificationDweller" DROP CONSTRAINT IF EXISTS "AddressEdificationDwellerAddressEdificationFK" CASCADE;
ALTER TABLE IF EXISTS "AddressEdificationDweller" DROP CONSTRAINT IF EXISTS "AddressEdificationDwellerSubjectFK" CASCADE;
ALTER TABLE IF EXISTS "AddressEdificationDweller" DROP CONSTRAINT IF EXISTS "AddressEdificationDwellerVerifiedByFK" CASCADE;

ALTER TABLE IF EXISTS "City" DROP CONSTRAINT IF EXISTS "CityStateFK" CASCADE;

ALTER TABLE IF EXISTS "Government" DROP CONSTRAINT IF EXISTS "GovernmentOrganizationFK" CASCADE;

ALTER TABLE IF EXISTS "GovernmentCity" DROP CONSTRAINT IF EXISTS "GovernmentCityGovernmentFK" CASCADE;
ALTER TABLE IF EXISTS "GovernmentCity" DROP CONSTRAINT IF EXISTS "GovernmentCityCityFK" CASCADE;

ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualSubjectFK" CASCADE;
ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualRgAgencyFK" CASCADE;
ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualRgStateFK" CASCADE;
ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualBirthPlaceFK" CASCADE;

ALTER TABLE IF EXISTS "Organization" DROP CONSTRAINT IF EXISTS "OrganizationSubjectFK" CASCADE;

ALTER TABLE IF EXISTS "State" DROP CONSTRAINT IF EXISTS "StateCountryFK" CASCADE;

ALTER TABLE IF EXISTS "SubjectSubject" DROP CONSTRAINT IF EXISTS "SubjectSubjectParentFK" CASCADE;
ALTER TABLE IF EXISTS "SubjectSubject" DROP CONSTRAINT IF EXISTS "SubjectSubjectChildFK" CASCADE;

ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenGovernmentFK" CASCADE;
ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenUserFK" CASCADE;
ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenSubjectSubjectFK" CASCADE;

ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserIndividualFK" CASCADE;
ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserLastLoggedInFK" CASCADE;

ALTER TABLE IF EXISTS "ModifiedAddress" DROP CONSTRAINT IF EXISTS "ModifiedAddressCityFK" CASCADE;
ALTER TABLE IF EXISTS "ModifiedAddress" DROP CONSTRAINT IF EXISTS "ModifiedAddressModifiedByFK" CASCADE;
ALTER TABLE IF EXISTS "ModifiedAddress" DROP CONSTRAINT IF EXISTS "ModifiedAddressAddressFK" CASCADE;

ALTER TABLE IF EXISTS "ModifiedAddressEdification" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationModifiedAddressFK" CASCADE;
ALTER TABLE IF EXISTS "ModifiedAddressEdification" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationTypeFK" CASCADE;

ALTER TABLE IF EXISTS "ModifiedAddressEdificationDweller" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationDwellerModifiedAddressEdificationFK" CASCADE;
ALTER TABLE IF EXISTS "ModifiedAddressEdificationDweller" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationDwellerSubjectFK" CASCADE;
ALTER TABLE IF EXISTS "ModifiedAddressEdificationDweller" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationDwellerRgAgencyFK" CASCADE;
ALTER TABLE IF EXISTS "ModifiedAddressEdificationDweller" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationDwellerRgStateFK" CASCADE;
ALTER TABLE IF EXISTS "ModifiedAddressEdificationDweller" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationDwellerBirthPlaceFK" CASCADE;

/*PRIMARY KEYS*/

ALTER TABLE IF EXISTS "Type" DROP CONSTRAINT IF EXISTS "TypePK" CASCADE;

ALTER TABLE IF EXISTS "Address" DROP CONSTRAINT IF EXISTS "AddressPK" CASCADE;

ALTER TABLE IF EXISTS "AddressEdification" DROP CONSTRAINT IF EXISTS "AddressEdificationPK" CASCADE;

ALTER TABLE IF EXISTS "AddressEdificationDweller" DROP CONSTRAINT IF EXISTS "AddressEdificationDwellerPK" CASCADE;

ALTER TABLE IF EXISTS "Agency" DROP CONSTRAINT IF EXISTS "AgencyPK" CASCADE;

ALTER TABLE IF EXISTS "City" DROP CONSTRAINT IF EXISTS "CityPK" CASCADE;

ALTER TABLE IF EXISTS "Country" DROP CONSTRAINT IF EXISTS "CountryPK" CASCADE;

ALTER TABLE IF EXISTS "Government" DROP CONSTRAINT IF EXISTS "GovernmentPK" CASCADE;

ALTER TABLE IF EXISTS "GovernmentCity" DROP CONSTRAINT IF EXISTS "GovernmentCityPK" CASCADE;

ALTER TABLE IF EXISTS "Individual" DROP CONSTRAINT IF EXISTS "IndividualPK" CASCADE;

ALTER TABLE IF EXISTS "Organization" DROP CONSTRAINT IF EXISTS "OrganizationPK" CASCADE;

ALTER TABLE IF EXISTS "State" DROP CONSTRAINT IF EXISTS "StatePK" CASCADE;

ALTER TABLE IF EXISTS "Subject" DROP CONSTRAINT IF EXISTS "SubjectPK" CASCADE;

ALTER TABLE IF EXISTS "SubjectSubject" DROP CONSTRAINT IF EXISTS "SubjectSubjectPK" CASCADE;

ALTER TABLE IF EXISTS "Token" DROP CONSTRAINT IF EXISTS "TokenPK" CASCADE;

ALTER TABLE IF EXISTS "User" DROP CONSTRAINT IF EXISTS "UserPK" CASCADE;

ALTER TABLE IF EXISTS "ModifiedAddress" DROP CONSTRAINT IF EXISTS "ModifiedAddressPK" CASCADE;

ALTER TABLE IF EXISTS "ModifiedAddressEdification" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationPK" CASCADE;

ALTER TABLE IF EXISTS "ModifiedAddressEdificationDweller" DROP CONSTRAINT IF EXISTS "ModifiedAddressEdificationDwellerPK" CASCADE;
